name: sending email every 5 minutes
on: 
  schedule:
    - cron: '*/5 * * * *'

jobs: 
  sending_email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check repo
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: install dependencies
      run: |
       pip install -r requirements.txt


    - name: run python file
      run: python send_email.py


